# vlt-chatbot/fly.toml
app = "vlt-chatbot"
primary_region = "sin"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false   # luôn bật
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval     = "15s"
    timeout      = "60s"
    grace_period = "60s"
    method       = "GET"
    path         = "/health"
    protocol     = "http"

[[vm]]
  cpu_kind  = "shared"
  cpus      = 1
  memory_mb = 256

[env]
  PROFILE_PATH = "data/profile.json"
  OMP_NUM_THREADS = "1"
  MKL_NUM_THREADS = "1"
