app = "vlt-chatbot"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true        # <— tự tắt khi rảnh
  auto_start_machines = true
  min_machines_running = 0         # <— cho phép về 0
  strategy = "immediate"

  [[http_service.checks]]
    interval     = "15s"
    timeout      = "60s"
    grace_period = "60s"
    method       = "GET"
    path         = "/health"
    protocol     = "http"

[[vm]]
  cpu_kind  = "shared"
  cpus      = 1
  memory_mb = 512                  # <— bắt đầu với 512MB; nếu OOM, đổi lại 1024

[env]
  PROFILE_PATH = "data/profile.json"
